### ISSUE TITLE
Raft WSL stuck on getting distros

### ISSUE THREAD

**Issue by SeeEyei** [vinberg88/opensuse#1]
I reinstalled WSL2 on Windows 11 and restarted the computer and it still didn't work

**Comment by vinberg88** [comment]
See if there is any solution. Have problems after reinstallation. Had to reinstall all of Windows 11 and now it won't work.

**Comment by vinberg88** [comment]
Here you have =] you need to do this after installation.

EXTRA EXTRA: If you can't get gwsl to work "X server" This is a good way.

sudo nano /etc/wsl.conf

Add this to terminal and save and REBOOT

[network]
generateHosts = true
generateResolvConf = false

Add this to terminal - save and reboot - Now GWSL works with sound

sudo nano /etc/resolv.conf

nameserver 172.18.112.1

Regards,
Mattias Vinberg
