### ISSUE TITLE
what i need to change if i have amd video card ? 

### ISSUE THREAD

**Issue by Redisal** [vinberg88/opensuse#2]
ln -s libcuda.so.1.1 libcuda.so.1
ln -s libcuda.so.1.1 libcuda.so
echo -e "[automount]\nldconfig = false" | sudo tee -a /etc/wsl.conf
sudo mkdir /usr/lib/wsl/lib2
sudo ln -s /usr/lib/wsl/lib/* /usr/lib/wsl/lib2
echo /usr/lib/wsl/lib2 | sudo tee /etc/ld.so.conf.d/ld.wsl.conf

**Comment by vinberg88** [comment]
You need to speak to WSL.... I dont want you to have problems =)

**Comment by vinberg88** [comment]
You dont need to paste that in Bash... its up to you...
