### ISSUE TITLE
can't start desktop environment

### ISSUE THREAD

**Issue by andrea1199** [vinberg88/opensuse#3]
right now noone of the DE i tried on ubuntu are working. i am using last wsl verision. idk why fastfetch/nofetch&hyfetch don't recognise anymore my vcard (NVIDIA) with correct setted up drivers. this is my envirnonment : wsl -v
Versione WSL: 2.2.4.0
Versione kernel: 5.15.153.1-2
Versione WSLg: 1.0.61
Versione MSRDC: 1.2.5326
Versione Direct3D: 1.611.1-81528511
Versione DXCore: 10.0.26091.1-240325-1447.ge-release
Versione di Windows: 10.0.22631.3737
can you please help me, i use it for months but i had to reset my pc and now i can't install.
i have gwl and using wsl --shutdown to restart 'couse i am not using raft. followed every yt tutorial, every ubuntu related guide here but i never got the DE started. if possible give me something on ubuntu 24.04. the kde-standard is the best one for me.
if you need any screenshoot or a stream u can reach me on discord as andrea1199
common errors i get are about the port or in some cases everything got stuck

**Comment by vinberg88** [comment]
Have also had to reinstall the whole windows 11 and now it doesn't work....

I am talking to GWSL maker and WSL.. See if there is any solution

**Comment by andrea1199** [comment]
Just un update, in case u didn’t notice. The problem is not in gwsl but in wsl. Now the application is called wslg and maybe it has his own “xserver” or what it is. I think nothing can be done to have full desk environment. I enjoyed your videos and solution but i fell like Microsoft has different plans Inviato da Posta per Windows Da: Mattias VinbergInviato: mercoledì 19 giugno 2024 17:35A: vinberg88/opensuseCc: Andrea; AuthorOggetto: Re: [vinberg88/opensuse] can't start desktop environment (Issue #3) Have also had to reinstall the whole windows 11 and now it doesn't work....I am talking to GWSL maker and WSL.. See if there is any solution—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by vinberg88** [comment]
Work Around -- Type before calling gnome - Kde...... Works =)

export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print $4}'):0.0

**Comment by andrea1199** [comment]
update, most important part is to disable wslg protocol in %UserProfile% crating a file named .wslconfig and typing "[wsl2]
guiApplications=false"
