### ISSUE TITLE
Tumbleweed wsl2 script, desktop crashes on start

### ISSUE THREAD

**Issue by jdmaltz** [vinberg88/opensuse#4]
upon entering the command dbus-launch startplasma-x11 after set up the desktop beings to startup but crashes out with the following error.

X11 backend not detected. Exit.
org.kde.startup: "kapplymousetheme" QList("breeze_cursors", "24") exited with code 2
Initializing  "/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_fonts.so"
Initializing  "/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_style.so"
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
Initializing  "/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_mouse.so"
kcm_mouse: Error on receiving device list from KWin.
org.kde.plasma.session: process job  "kcminit_startup" finished with exit code  0
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
layershellqt: Failed to initialize layer-shell integration, possibly because compositor does not support the layer-shell protocol
layershellqt: Failed to initialize layer-shell integration, possibly because compositor does not support the layer-shell protocol
layershellqt: Failed to initialize layer-shell integration, possibly because compositor does not support the layer-shell protocol
org.kde.kameleon: found no RGB LED devices
Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kglobalaccel was not provided by any .service files")
kf.bluezqt: Cannot open /dev/rfkill for reading!
org.kde.colorcorrectlocationupdater: Geolocator stopped
QDBusObjectPath: invalid path "/modules/plasma-session-shortcuts"
kf.dbusaddons: The kded module name "plasma-session-shortcuts" is invalid!
kwin: unable to claim manager selection, another wm running? (try using --replace)
org.kde.libkbolt: Failed to connect to Bolt manager DBus interface: The name org.freedesktop.NetworkManager was not provided by any .service files
org.kde.bolt.kded: Couldn't connect to Bolt DBus daemon
org.kde.plasma.printmanager.kded: unable to register service to dbus
kf.config.kconf_update: /usr/share/kconf_update/ark.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/dolphin_detailsmodesettings.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/dolphin_directorysizemode.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/filepicker.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/konsole.upd defined Version=5 but Version=6 was expected
kf.config.kconf_update: /usr/share/kconf_update/okular.upd defined Version=5 but Version=6 was expected
kf.modemmanagerqt: Failed enumerating MM objects: "org.freedesktop.DBus.Error.TimedOut"

**Comment by vinberg88** [comment]
Hi Mate

Will try to fix that after work.

**Comment by vinberg88** [comment]
https://www.youtube.com/watch?v=418r2xhrBWQ

**Comment by vinberg88** [comment]
Look at video and try =)
